apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: probe-test
spec:
  containers:
  - name: probe-test
    image: probe-test:1.0
    livenessProbe:
      tcpSocket:
        port: 9000
      initialDelaySeconds: 10
      periodSeconds: 20
