on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Read Version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./version.txt
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet build src/AnvilCloud.Kubernetes.Probes.sln --configuration Release /p:Version="${{ steps.version.outputs.content }}"
    - name: pack Probes
      run: dotnet pack src/AnvilCloud.Kubernetes.Probes/AnvilCloud.Kubernetes.Probes.csproj --configuration Release --no-build --no-restore /p:Version="${{ steps.version.outputs.content }}"
    - name: pack Probes.Tcp
      run: dotnet pack src/AnvilCloud.Kubernetes.Probes.Tcp/AnvilCloud.Kubernetes.Probes.Tcp.csproj --configuration Release --no-build --no-restore /p:Version="${{ steps.version.outputs.content }}"
    - name: Publish nuget
      run: dotnet nuget push src/**/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
    
